# -*- coding: utf-8 -*-
"""Метаданные песен (название RU/EN, исполнители, тональность).

Генерируется tools/extract_meta.py, затем правится вручную.
Ключ — имя файла в songs/.
"""

SONG_META = {
    'agnec-i-lev-bethel-music-lion-and-the-lamb.md': {
        'title_ru': 'Агнец и лев',
        'title_en': 'Lion and the lamb',
        'key': 'G',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'allilujya-nuteki-worship.md': {
        'title_ru': 'Аллилуйя',
        'title_en': '',
        'key': 'G',
        'artists': ['Nuteki Worship'],
        'alt_titles': [],
    },
    'ashem-meleh-derech.md': {
        'title_ru': 'Ашэм мэлэх',
        'title_en': '',
        'key': 'A',
        'artists': ['Derech'],
        'alt_titles': [],
    },
    'avva-otche-lyublyu-tebya.md': {
        'title_ru': 'Авва, Отче, люблю Тебя',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'baruh-adonaj-paul-wilbur-baruch-adonai.md': {
        'title_ru': 'Барух Адонай',
        'title_en': 'Baruch Adonai',
        'key': '',
        'artists': ['Paul Wilbur'],
        'alt_titles': [],
    },
    'bez-konca-budu-pet-kak-spasena-dusha.md': {
        'title_ru': 'Без конца буду петь, как спасена душа',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'blago-budet-imya-ego-e.md': {
        'title_ru': 'Благо будет Имя Его',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'blagodaryu-tebya-iisus.md': {
        'title_ru': 'Благодарю Тебя, Иисус',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'blagoslovi-dusha-moya-gospoda.md': {
        'title_ru': 'Благослови душа моя, Господа',
        'title_en': '',
        'key': '',
        'artists': [],
        'alt_titles': [],
    },
    'bog-ischu-tebya-bethel-music-god-i-look-to-you.md': {
        'title_ru': 'Бог, ищу Тебя',
        'title_en': 'God I look to You',
        'key': 'C',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'bog-silnyj-bethel-music-waymaker.md': {
        'title_ru': 'Бог сильный',
        'title_en': 'Waymaker',
        'key': 'A',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'bog-tvoryaschij-chudesa-jesus-culture-miracles.md': {
        'title_ru': 'Бог творящий чудеса',
        'title_en': 'Miracles',
        'key': 'Em',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'bog-vsego-zhivogo-third-day-god-of-wonders.md': {
        'title_ru': 'Бог всего живого',
        'title_en': 'God of Wonders',
        'key': 'G',
        'artists': ['Third Day'],
        'alt_titles': [],
    },
    'bog-zhivoj-slovo-zhizni.md': {
        'title_ru': 'Бог живой',
        'title_en': '',
        'key': 'D',
        'artists': ['Слово Жизни'],
        'alt_titles': [],
    },
    'bozhe-nash-velikij-valerij-korop.md': {
        'title_ru': 'Боже наш великий',
        'title_en': '',
        'key': 'G',
        'artists': ['Валерий Короп'],
        'alt_titles': [],
    },
    'bozhe-net-tebya-dorozhe.md': {
        'title_ru': 'Боже, нет Тебя дороже',
        'title_en': '',
        'key': 'Hm',
        'artists': [],
        'alt_titles': [],
    },
    'bud-dlya-menya-viktor-lavrinenko-g-68.md': {
        'title_ru': 'Будь для меня',
        'title_en': '',
        'key': 'G (6/8)',
        'artists': ['Виктор Лавриненко'],
        'alt_titles': [],
    },
    'budem-poklonyatsya-slovo-zhizni.md': {
        'title_ru': 'Будем поклоняться',
        'title_en': '',
        'key': 'G',
        'artists': ['Слово Жизни'],
        'alt_titles': [],
    },
    'budu-pogruzhatsya-sokolovbrothers.md': {
        'title_ru': 'Буду погружаться',
        'title_en': '',
        'key': 'Gm',
        'artists': ['SokolovBrothers'],
        'alt_titles': [],
    },
    'car-serdca-moego-bethel-music-king-of-my-heart.md': {
        'title_ru': 'Царь сердца моего',
        'title_en': 'King of my heart',
        'key': 'G',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'car-velichiya-hillsong-worship-king-of-majesty.md': {
        'title_ru': 'Царь Величия',
        'title_en': 'King of Majesty',
        'key': 'G',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'carstvuet-nash-gospod-agnus-dei.md': {
        'title_ru': 'Царствует наш Господь',
        'title_en': 'Agnus Dei',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'celitel-hillsong-healer.md': {
        'title_ru': 'Целитель',
        'title_en': 'Healer',
        'key': 'G',
        'artists': ['Hillsong'],
        'alt_titles': [],
    },
    'chudesna-blagodat-bethel-music-this-is-amazing-grace.md': {
        'title_ru': 'Чудесна благодать',
        'title_en': 'This is amazing grace',
        'key': 'C',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'da-da-iisusa-ya-lyublyu.md': {
        'title_ru': 'Да, да, Иисуса я люблю',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'da-slavit-dusha-moya-tebya-kraeugolnyj-kamen.md': {
        'title_ru': 'Да славит душа моя Тебя',
        'title_en': '',
        'key': 'D',
        'artists': ['Краеугольный камень'],
        'alt_titles': [],
    },
    'davaj-tancevat.md': {
        'title_ru': 'Давай танцевать',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'davajte-vmeste-slavit-boga.md': {
        'title_ru': 'Давайте вместе славить Бога',
        'title_en': '',
        'key': 'D',
        'artists': [],
        'alt_titles': [],
    },
    'den-pyatidesyatnicy.md': {
        'title_ru': 'День пятидесятницы',
        'title_en': '',
        'key': 'D',
        'artists': [],
        'alt_titles': [],
    },
    'dip-dip-unknown-artist-g.md': {
        'title_ru': 'Дип-дип',
        'title_en': '',
        'key': 'G',
        'artists': ['Unknown artist'],
        'alt_titles': [],
    },
    'ditya-carya-hillsong-kids-royalty.md': {
        'title_ru': 'Дитя Царя',
        'title_en': 'Royalty',
        'key': 'E',
        'artists': ['Hillsong Kids'],
        'alt_titles': [],
    },
    'dlya-tebya-hillsong.md': {
        'title_ru': 'Для Тебя',
        'title_en': '',
        'key': 'G',
        'artists': ['Hillsong'],
        'alt_titles': [],
    },
    'drugom-menya-nazval-israel-houghton-friend-of-god.md': {
        'title_ru': 'Другом меня назвал',
        'title_en': 'Friend of God',
        'key': 'E',
        'artists': ['Israel Houghton'],
        'alt_titles': [],
    },
    'duh-gospoden-na-mne-rcc-worship.md': {
        'title_ru': 'Дух Господень на мне',
        'title_en': '',
        'key': 'D',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'duh-svyatoj-soshel-na-zemlyu.md': {
        'title_ru': 'Дух Святой сошёл на Землю',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'duhom-obnovi-a.md': {
        'title_ru': 'Духом обнови',
        'title_en': '',
        'key': 'A',
        'artists': [],
        'alt_titles': [],
    },
    'egipet-bethel-music-egypt.md': {
        'title_ru': 'Египет',
        'title_en': 'Egypt',
        'key': 'Em',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'ego-imya-iisus-jeremy-riddle-his-name-is-jesus.md': {
        'title_ru': 'Его имя Иисус',
        'title_en': 'His name is Jesus',
        'key': 'Dm',
        'artists': ['Jeremy Riddle'],
        'alt_titles': [],
    },
    'elisej-rcc-worship.md': {
        'title_ru': 'Елисей',
        'title_en': '',
        'key': 'D',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'emu-podobnyh-net-bethel-music-no-one-like-the-lord.md': {
        'title_ru': 'Ему подобных нет',
        'title_en': 'No one like the Lord',
        'key': 'Am',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'esli-syn-osvobodil-onething-live-whom-the-son-sets-free.md': {
        'title_ru': 'Если Сын освободил',
        'title_en': 'Whom the Son sets free',
        'key': 'G',
        'artists': ['Onething Live'],
        'alt_titles': [],
    },
    'eto-sila-there-is-power.md': {
        'title_ru': 'Это Сила',
        'title_en': 'There is Power',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'etot-den-sotvoril-gospod-keith-green-this-is-the-day.md': {
        'title_ru': 'Этот день сотворил Господь',
        'title_en': 'This is the day',
        'key': 'D',
        'artists': ['Keith Green'],
        'alt_titles': [],
    },
    'gluboko-v-tebe-bethel-music-deep-cries-out-g.md': {
        'title_ru': 'Глубоко в Тебе',
        'title_en': 'Deep Cries Out',
        'key': 'G*',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'golgofa-hillsong-united-calvary.md': {
        'title_ru': 'Голгофа',
        'title_en': 'Calvary',
        'key': 'G',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'govori-slovo-zhizni.md': {
        'title_ru': 'Говори',
        'title_en': '',
        'key': 'G',
        'artists': ['Слово Жизни'],
        'alt_titles': [],
    },
    'hava-nagila.md': {
        'title_ru': 'Хава Нагила',
        'title_en': '',
        'key': 'Am',
        'artists': [],
        'alt_titles': [],
    },
    'hillsong-v-tebe-vsya-zhizn-moya-tebya-ne-perestanu-slavit.md': {
        'title_ru': 'В Тебе вся жизнь моя',
        'title_en': '',
        'key': 'G',
        'artists': ['Hillsong'],
        'alt_titles': ['Тебя не перестану славить'],
    },
    'hochu-ya-znat-tebya-sonicflood-i-want-to-know-you.md': {
        'title_ru': 'Хочу я знать Тебя',
        'title_en': 'I want to know You',
        'key': 'G',
        'artists': ['Sonicflood'],
        'alt_titles': [],
    },
    'hristos-vo-mne-viktor-lavrinenko.md': {
        'title_ru': 'Христос во мне',
        'title_en': '',
        'key': 'A',
        'artists': ['Виктор Лавриненко'],
        'alt_titles': [],
    },
    'hvala-hillsong.md': {
        'title_ru': 'Хвала',
        'title_en': '',
        'key': 'G',
        'artists': ['Hillsong'],
        'alt_titles': [],
    },
    'hvala-na-ustah-moih-bethel-music-ever-be.md': {
        'title_ru': 'Хвала на устах моих',
        'title_en': 'Ever be',
        'key': 'D',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'hvalite-gospoda-vse-narody-selah-a.md': {
        'title_ru': 'Хвалите Господа, все народы',
        'title_en': '',
        'key': 'A',
        'artists': ['Селах'],
        'alt_titles': [],
    },
    'ieshua.md': {
        'title_ru': 'Иешуа',
        'title_en': '',
        'key': 'Am',
        'artists': [],
        'alt_titles': ['Кто, как Ты'],
    },
    'iisus-moj-drug-not-an-idol.md': {
        'title_ru': 'Иисус - мой Друг',
        'title_en': 'Not an Idol',
        'key': 'Dm',
        'artists': ['Not an Idol'],
        'alt_titles': [],
    },
    'iisus-moj-supergeroj-hillsong-kids-jesus-is-my-superhero.md': {
        'title_ru': 'Иисус - мой супергерой',
        'title_en': 'Jesus is my superhero',
        'key': 'D',
        'artists': ['Hillsong Kids'],
        'alt_titles': [],
    },
    'iisus-na-trone.md': {
        'title_ru': 'Иисус на троне',
        'title_en': '',
        'key': 'D',
        'artists': [],
        'alt_titles': [],
    },
    'iisus-prekrasen-ty-carleigh-conant-beautiful-and-glorious.md': {
        'title_ru': 'Иисус, прекрасен Ты',
        'title_en': 'Beautiful and Glorious',
        'key': 'Hm',
        'artists': ['Carleigh Conant'],
        'alt_titles': [],
    },
    'iisus-prevoznosim-tvoe-imya-ty-car-don-moen-jesus-we-enthron.md': {
        'title_ru': 'Иисус, превозносим, Твоё имя, Ты царь',
        'title_en': 'Jesus We Enthrone You',
        'key': 'Em',
        'artists': ['Don Moen'],
        'alt_titles': [],
    },
    'iisus-skala.md': {
        'title_ru': 'Иисус - скала',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'iisus-tak-nuzhen-mne-rcc-worship.md': {
        'title_ru': 'Иисус так нужен мне',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'iisus-ty-lyubov-moya-hillsong-worship-jesus-lover-of-my-soul.md': {
        'title_ru': 'Иисус, Ты любовь моя',
        'title_en': 'Jesus Lover of my soul',
        'key': 'G',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'izlej-ot-duha-reallife-band.md': {
        'title_ru': 'Излей от Духа',
        'title_en': '',
        'key': 'Em',
        'artists': ['Reallife band'],
        'alt_titles': [],
    },
    'izlivaj-pour-it-out-hungrygen-worship.md': {
        'title_ru': 'Изливай',
        'title_en': 'Pour it Out',
        'key': 'C#m',
        'artists': ['Hungrygen Worship'],
        'alt_titles': [],
    },
    'kadosh.md': {
        'title_ru': 'Кадош',
        'title_en': '',
        'key': 'Am',
        'artists': [],
        'alt_titles': [],
    },
    'kak-ty-velik-hymn-how-great-thou-art.md': {
        'title_ru': 'Как Ты велик',
        'title_en': 'How Great Thou Art',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'kazhduyu-detal-hillsong-yf-every-little-thing.md': {
        'title_ru': 'Каждую деталь',
        'title_en': 'Every Little Thing',
        'key': 'G',
        'artists': ['Hillsong Y&F'],
        'alt_titles': [],
    },
    'kogda-my-vmeste-rcc-worship.md': {
        'title_ru': 'Когда мы вместе',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'kogda-stihnet-vse-michael-w-smith-heart-of-worship.md': {
        'title_ru': 'Когда стихнет всё',
        'title_en': 'Heart of Worship',
        'key': 'C',
        'artists': ['Michael W. Smith'],
        'alt_titles': [],
    },
    'kresti-menya-svoej-siloj-generacion-12-baptzame.md': {
        'title_ru': 'Крести меня Своей силой',
        'title_en': 'Baptízame',
        'key': 'C#m',
        'artists': ['Generacion 12'],
        'alt_titles': [],
    },
    'krov-hrista-krov-krov-chto-omyla-nas.md': {
        'title_ru': 'Кровь Христа',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': ['Кровь, кровь что омыла нас'],
    },
    'lish-hristos-kamen-moj-hillsong-worship-cornerstone.md': {
        'title_ru': 'Лишь Христос - камень мой',
        'title_en': 'Cornerstone',
        'key': 'A',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'lish-v-rukah-tvoih-prizhmus-k-tvoej-ladoni.md': {
        'title_ru': 'Лишь в руках Твоих',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': ['Прижмусь к Твоей ладони'],
    },
    'lyublyu-banany-unknown-artist-i-like-bananas-g.md': {
        'title_ru': 'Люблю бананы',
        'title_en': 'I like bananas',
        'key': 'G',
        'artists': ['Unknown artist'],
        'alt_titles': [],
    },
    'lyubov-beskonechna-hillsong-united-relentless-n.md': {
        'title_ru': 'Любовь бесконечна',
        'title_en': 'Relentless',
        'key': 'H',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'lyubov-tvoya-o-gospod-beskonechna-oni-prihodyat-s-kazhdym-ut.md': {
        'title_ru': 'Любовь Твоя, о, Господь, бесконечна',
        'title_en': '',
        'key': 'D',
        'artists': [],
        'alt_titles': ['Они приходят с каждым утром'],
    },
    'lyubov-tvoya-velika-ark-worship.md': {
        'title_ru': 'Любовь Твоя велика',
        'title_en': '',
        'key': 'G',
        'artists': ['ARK WORSHIP'],
        'alt_titles': [],
    },
    'lyubov-tvoya-verna-jesus-culture-your-love-never-fails.md': {
        'title_ru': 'Любовь Твоя Верна',
        'title_en': 'Your Love Never Fails',
        'key': 'G',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'lyubov-vojna-hillsong-united-love-is-war.md': {
        'title_ru': 'Любовь - война',
        'title_en': 'Love is War',
        'key': 'Hb',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'menyaesh-atmosferu-v-nas-elevation-worship-here-as-in-heaven.md': {
        'title_ru': 'Меняешь атмосферу в нас',
        'title_en': 'Here as in Heaven',
        'key': 'C',
        'artists': ['Elevation Worship'],
        'alt_titles': [],
    },
    'moe-serdce-slovo-zhizni-e.md': {
        'title_ru': 'Моё сердце',
        'title_en': '',
        'key': 'E',
        'artists': ['Слово Жизни'],
        'alt_titles': [],
    },
    'my-k-tebe-vozzovem-vozmi-menya-v-gory-filipp-renner.md': {
        'title_ru': 'Мы к Тебе воззовём / Возьми меня в горы',
        'title_en': '',
        'key': 'G',
        'artists': ['Филипп Реннер'],
        'alt_titles': [],
    },
    'my-odna-semya-e.md': {
        'title_ru': 'Мы одна семья',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'my-slavim-tebya-rcc-worship.md': {
        'title_ru': 'Мы славим Тебя',
        'title_en': '',
        'key': 'H',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'my-vosklicaem-hillsong-shout-unto-god.md': {
        'title_ru': 'Мы восклицаем',
        'title_en': 'Shout Unto God',
        'key': 'A',
        'artists': ['Hillsong'],
        'alt_titles': [],
    },
    'my-zhdem-tebya-shekinah-glory.md': {
        'title_ru': 'Мы ждём Тебя',
        'title_en': '',
        'key': 'G',
        'artists': ['Shekinah Glory'],
        'alt_titles': [],
    },
    'na-shag-blizhe-k-tebe-filipp-renner.md': {
        'title_ru': 'На шаг ближе к Тебе',
        'title_en': '',
        'key': 'G',
        'artists': ['Филипп Реннер'],
        'alt_titles': [],
    },
    'nadezhda-v-tebe-third-day-my-hope-is-you.md': {
        'title_ru': 'Надежда в Тебе',
        'title_en': 'My hope is You',
        'key': 'E',
        'artists': ['Third Day'],
        'alt_titles': [],
    },
    'napoi-menya.md': {
        'title_ru': 'Напои меня',
        'title_en': '',
        'key': 'Hm',
        'artists': [],
        'alt_titles': [],
    },
    'narody-rcc-worship.md': {
        'title_ru': 'НАРОДЫ',
        'title_en': '',
        'key': 'D',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'nash-bog-tak-velik-chris-tomlin-how-great-is-our-god.md': {
        'title_ru': 'Наш Бог так велик',
        'title_en': 'How great is our God',
        'key': 'G',
        'artists': ['Chris Tomlin'],
        'alt_titles': [],
    },
    'nash-bog-vsemoguschij-hillsong-united-awesome-god.md': {
        'title_ru': 'Наш Бог Всемогущий',
        'title_en': 'Awesome God',
        'key': 'E',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'ne-ostanovlyus-ya-misty-edwards-only-a-shadow.md': {
        'title_ru': 'Не остановлюсь я',
        'title_en': 'Only a Shadow',
        'key': 'D',
        'artists': ['Misty Edwards'],
        'alt_titles': [],
    },
    'ne-umru-ya-no-budu.md': {
        'title_ru': 'Не умру я, но буду',
        'title_en': '',
        'key': 'F#m',
        'artists': [],
        'alt_titles': [],
    },
    'nichego-net-luchshe-chem-ty-elevation-worship-graves-into-ga.md': {
        'title_ru': 'Ничего нет лучше, чем Ты',
        'title_en': 'Graves into gardens',
        'key': 'G (6/8)',
        'artists': ['Elevation Worship'],
        'alt_titles': [],
    },
    'nichego-net-nevozmozhnogo-nothing-is-impossible.md': {
        'title_ru': 'Ничего нет невозможного',
        'title_en': 'Nothing is impossible',
        'key': 'A',
        'artists': [],
        'alt_titles': [],
    },
    'nikogda-matt-redman-never-once.md': {
        'title_ru': 'Никогда',
        'title_en': 'Never Once',
        'key': 'G',
        'artists': ['Matt Redman'],
        'alt_titles': [],
    },
    'nuzhen-mne-lish-ty-hillsong-worship-all-i-need-is-you.md': {
        'title_ru': 'Нужен мне лишь Ты',
        'title_en': 'All I need is You',
        'key': 'Am',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'o-blagodat-4u-band.md': {
        'title_ru': 'О, Благодать',
        'title_en': '',
        'key': 'D',
        'artists': ['4U Band'],
        'alt_titles': [],
    },
    'o-etot-den-voice-of-childrens-choir-oh-happy-day.md': {
        'title_ru': 'О, этот день',
        'title_en': 'Oh, Happy Day',
        'key': 'E',
        'artists': ['Voice of Children’s Choir'],
        'alt_titles': [],
    },
    'o-gospod-tebe-my-poem-bethel-music-to-our-god.md': {
        'title_ru': 'О, Господь, Тебе мы поём',
        'title_en': 'To our God',
        'key': 'Em',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'o-gospod-ty-prizval.md': {
        'title_ru': 'О, Господь, Ты призвал',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'o-kak-on-lyubit-nas-crowder-how-he-loves-us.md': {
        'title_ru': 'О, как Он любит нас',
        'title_en': 'How He loves us',
        'key': 'G',
        'artists': ['Crowder'],
        'alt_titles': [],
    },
    'o-lyubvi-tvoej-pet-budu-vechno-delirious-i-could-sing-of-you.md': {
        'title_ru': 'О любви Твоей петь буду вечно',
        'title_en': 'I could sing of Your love',
        'key': 'F',
        'artists': ['Delirious?'],
        'alt_titles': [],
    },
    'o-nichto-lish-krov-iisusa.md': {
        'title_ru': 'О, ничто лишь кровь Иисуса',
        'title_en': '',
        'key': 'A',
        'artists': [],
        'alt_titles': [],
    },
    'o-proslavlyaj-imya-gospoda-hillsong-worship-o-praise-the-nam.md': {
        'title_ru': 'О, прославляй имя Господа',
        'title_en': 'O, praise the Name',
        'key': 'A',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'obratis-k-iisusu.md': {
        'title_ru': 'Обратись к Иисусу',
        'title_en': '',
        'key': 'D',
        'artists': [],
        'alt_titles': [],
    },
    'odin-put-iisus-hillsong-united-one-way.md': {
        'title_ru': 'Один путь - Иисус',
        'title_en': 'One way',
        'key': 'Hb',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'osanna-hillsong-worship-hosanna.md': {
        'title_ru': 'Осанна',
        'title_en': 'Hosanna',
        'key': 'C#m',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'osveschaesh-rcc-worship-hm-temp-118.md': {
        'title_ru': 'Освещаешь',
        'title_en': '',
        'key': 'Hm (Темп - 118)',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'otec-nash-bethel-music-our-father.md': {
        'title_ru': 'Отец наш',
        'title_en': 'Our Father',
        'key': 'G',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'otkroj-mne-glaza.md': {
        'title_ru': 'Открой мне глаза',
        'title_en': '',
        'key': 'Hb',
        'artists': [],
        'alt_titles': [],
    },
    'otkroj-nebesa-rcc-worship.md': {
        'title_ru': 'Открой Небеса',
        'title_en': '',
        'key': 'A',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'pered-toboj-sklonyayus-ya.md': {
        'title_ru': 'Перед Тобой склоняюсь я',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'pet-budu-allilujya-bethel-music-raise-a-hallelujah.md': {
        'title_ru': 'Петь буду: "Аллилуйя!"',
        'title_en': 'Raise a Hallelujah',
        'key': 'A',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'poem-my-allilujya-rcc-worship-g.md': {
        'title_ru': 'Поём мы: «Аллилуйя!»',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'poem-o-tvoej-lyubvi-rcc-worship.md': {
        'title_ru': 'Поём о Твоей любви',
        'title_en': '',
        'key': 'Hb',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'poj-poj-dusha-argam-hachatryan.md': {
        'title_ru': 'Пой, пой душа',
        'title_en': '',
        'key': 'C#m',
        'artists': ['Аргам Хачатрян'],
        'alt_titles': [],
    },
    'poklonyus-tebe-sokolovbrothers.md': {
        'title_ru': 'Поклонюсь Тебе',
        'title_en': '',
        'key': 'G',
        'artists': ['SokolovBrothers'],
        'alt_titles': [],
    },
    'poklonyus-tebe.md': {
        'title_ru': 'Поклонюсь Тебе',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'pokoj-pust-bushuet-shtorm-hillsong-worship-still.md': {
        'title_ru': 'Покой',
        'title_en': 'Still',
        'key': 'E',
        'artists': ['Hillsong Worship'],
        'alt_titles': ['Пусть бушует шторм'],
    },
    'povedi-nas-v-glubiny-boga.md': {
        'title_ru': 'Поведи нас в глубины Бога',
        'title_en': '',
        'key': 'Hm',
        'artists': [],
        'alt_titles': [],
    },
    'pravit-bog-martin-smith-our-god-reigns.md': {
        'title_ru': 'Правит Бог',
        'title_en': 'Our God Reigns',
        'key': 'E',
        'artists': ['Martin Smith'],
        'alt_titles': [],
    },
    'prevoznesu-tebya-bethel-music-i-will-exalt-you.md': {
        'title_ru': 'Превознесу Тебя',
        'title_en': 'I will Exalt You',
        'key': 'A',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'prevoznosim-phil-driscoll-i-exalt-thee.md': {
        'title_ru': 'Превозносим',
        'title_en': 'I exalt thee',
        'key': 'A',
        'artists': ['Phil Driscoll'],
        'alt_titles': [],
    },
    'prevyshe-vseh-subcultura.md': {
        'title_ru': 'Превыше всех',
        'title_en': '',
        'key': 'G',
        'artists': ['Subcultura'],
        'alt_titles': [],
    },
    'pridi-duh-svyatoj-planetshakers-come-holy-spirit.md': {
        'title_ru': 'Приди Дух Святой',
        'title_en': 'Come Holy Spirit',
        'key': 'G',
        'artists': ['Planetshakers'],
        'alt_titles': [],
    },
    'pridi-ko-mne-bethel-music-come-to-me.md': {
        'title_ru': 'Приди ко Мне',
        'title_en': 'Come to me',
        'key': 'H',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'prihozhu-k-tebe-ya-terry-macalmon-you-deserve-the-glory.md': {
        'title_ru': 'Прихожу к Тебе я',
        'title_en': 'You Deserve the Glory',
        'key': 'A',
        'artists': ['Terry MacAlmon'],
        'alt_titles': [],
    },
    'prikosnis-ko-mne-i-menya-pokroj-kraeugolnyj-kamen.md': {
        'title_ru': 'Прикоснись ко Мне и меня покрой',
        'title_en': '',
        'key': 'Em',
        'artists': ['Краеугольный камень'],
        'alt_titles': [],
    },
    'prikosnovenie-nebes-hillsong-worship-touch-of-heaven.md': {
        'title_ru': 'Прикосновение Небес',
        'title_en': 'Touch of Heaven',
        'key': 'G',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'prinesem-probuzhdenie.md': {
        'title_ru': 'Принесём пробуждение',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'privodish-tmu-ty-v-trepet-mosaic-msc-tremble.md': {
        'title_ru': 'Приводишь тьму Ты в трепет',
        'title_en': 'Tremble',
        'key': 'D',
        'artists': ['Mosaic MSC'],
        'alt_titles': [],
    },
    'proslavlyaj-iisusa-proslavlyaj-don-moen-celebrate-jesus-cele.md': {
        'title_ru': 'Прославляй Иисуса, прославляй',
        'title_en': 'Celebrate Jesus, celebrate',
        'key': 'E',
        'artists': ['Don Moen'],
        'alt_titles': [],
    },
    'pryzhok-vpered.md': {
        'title_ru': 'Прыжок вперёд',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'psalom-32-rcc-worship.md': {
        'title_ru': 'Псалом 32',
        'title_en': '',
        'key': 'E',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'pust-budet-bolshe-tebya-menshe-menya-ya-tak-zhazhdu-roy-fiel.md': {
        'title_ru': 'Пусть будет больше Тебя, меньше меня',
        'title_en': 'Less of me',
        'key': 'G',
        'artists': ['Roy Fields'],
        'alt_titles': ['Я так жажду'],
    },
    'pust-gorit-tvoj-ogon-viktor-lavrinenko.md': {
        'title_ru': 'Пусть горит Твой огонь',
        'title_en': '',
        'key': 'D',
        'artists': ['Виктор Лавриненко'],
        'alt_titles': [],
    },
    'put-neemii-rcc-worship.md': {
        'title_ru': 'Путь Неемии',
        'title_en': '',
        'key': 'C#m',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'radujsya-mir-joy-to-world.md': {
        'title_ru': 'Радуйся мир',
        'title_en': 'Joy To World',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'raz-dva-tri-iisus-zhivoj-yancy-little-praise-party-one-two-t.md': {
        'title_ru': 'Раз, два, три, Иисус - живой',
        'title_en': 'One, Two, Three',
        'key': 'G',
        'artists': ['Yancy & Little Praise Party'],
        'alt_titles': [],
    },
    'reka-viktor-lavrinenko.md': {
        'title_ru': 'Река',
        'title_en': '',
        'key': 'G',
        'artists': ['Виктор Лавриненко'],
        'alt_titles': [],
    },
    'reki-isceleniya-rcc-worship.md': {
        'title_ru': 'Реки исцеления',
        'title_en': '',
        'key': 'F#m',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    's-angelami-v-nebe-slovo-zhizni-music.md': {
        'title_ru': 'С ангелами в Небе',
        'title_en': '',
        'key': 'A',
        'artists': ['Слово Жизни Music'],
        'alt_titles': [],
    },
    's-dnem-rozhdeniya-tebya-34.md': {
        'title_ru': 'С днём рождения тебя',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    's-etogo-momenta-hillsong-worship-pursue.md': {
        'title_ru': 'С этого момента',
        'title_en': 'Pursue',
        'key': 'C#m',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    's-neba-na-zemlyu-kraeugolnyj-kamen-ogon.md': {
        'title_ru': 'С неба на землю',
        'title_en': '',
        'key': 'C',
        'artists': ['Краеугольный камень'],
        'alt_titles': ['Огонь'],
    },
    'serdce-moe-otkryto-dlya-tebya.md': {
        'title_ru': 'Сердце моё открыто для Тебя',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'shtorm-john-thurlow-storm-all-around-you.md': {
        'title_ru': 'Шторм',
        'title_en': 'Storm all around You',
        'key': 'Em',
        'artists': ['John Thurlow'],
        'alt_titles': [],
    },
    'sila-v-ego-lyubvi-rcc-worship.md': {
        'title_ru': 'Сила в Его любви',
        'title_en': '',
        'key': 'D',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'silen-spasti-hillsong-united-mighty-to-save.md': {
        'title_ru': 'Силен спасти',
        'title_en': 'Mighty to save',
        'key': 'G',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'sklonyayas-my-kladem-vency-chris-tomlin-we-fall-down.md': {
        'title_ru': 'Склоняясь, мы кладём венцы',
        'title_en': 'We fall down',
        'key': 'D',
        'artists': ['Chris Tomlin'],
        'alt_titles': [],
    },
    'skvoz-veka-i-pokoleniya-be-enthroned-bethel-music.md': {
        'title_ru': 'Сквозь века и поколения',
        'title_en': 'Be Enthroned',
        'key': 'A',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'slav-elevation-worship-praise.md': {
        'title_ru': 'Славь',
        'title_en': 'Praise',
        'key': 'G',
        'artists': ['Elevation Worship'],
        'alt_titles': [],
    },
    'slava-v-vyshnih-bogu-angels-we-had-heard-on-high.md': {
        'title_ru': 'Слава в вышних Богу',
        'title_en': 'Angels we had heard on high',
        'key': 'D',
        'artists': [],
        'alt_titles': [],
    },
    'slaven-ty-gospod-elevation-worship-worthy.md': {
        'title_ru': 'Славен Ты, Господь',
        'title_en': 'Worthy',
        'key': 'D',
        'artists': ['Elevation Worship'],
        'alt_titles': [],
    },
    'slavlyu-imya-tvoe-rcc-worship.md': {
        'title_ru': 'Славлю Имя Твоё',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'slovno-reka-rcc-worship.md': {
        'title_ru': 'Словно река',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'snova-na-kolenyah-hillsong-came-to-my-rescue.md': {
        'title_ru': 'Снова на коленях',
        'title_en': 'Came to my rescue',
        'key': 'E',
        'artists': ['Hillsong'],
        'alt_titles': [],
    },
    'sozdal-nebo-slovo-zhizni-e.md': {
        'title_ru': 'Создал Небо',
        'title_en': '',
        'key': 'E',
        'artists': ['Слово Жизни'],
        'alt_titles': [],
    },
    'spasibo-bethel-music-thank-you.md': {
        'title_ru': 'Спасибо',
        'title_en': 'Thank You',
        'key': 'Bb',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'sredi-angelov-i-slavy-roy-fields-in-the-presence-of-angels.md': {
        'title_ru': 'Среди ангелов и славы',
        'title_en': 'In the presence of angels',
        'key': 'G',
        'artists': ['Roy Fields'],
        'alt_titles': [],
    },
    'steny-aleksandr-tihomirov-feat-eliza-belosevich-dirienko.md': {
        'title_ru': 'Стены',
        'title_en': '',
        'key': 'A',
        'artists': ['Александр Тихомиров', 'Элиза Белосевич-Дириенко'],
        'alt_titles': [],
    },
    'svobodny-my-planetshakers-we-are-free.md': {
        'title_ru': 'Свободны мы',
        'title_en': 'We are free',
        'key': 'A',
        'artists': ['Planetshakers'],
        'alt_titles': [],
    },
    'svobodu-nam-dal-matt-redman-we-are-free.md': {
        'title_ru': 'Свободу нам дал',
        'title_en': 'We Are Free',
        'key': 'G',
        'artists': ['Matt Redman'],
        'alt_titles': [],
    },
    'svyat-bog-svyaty-nebesa.md': {
        'title_ru': 'Свят Бог, святы небеса',
        'title_en': '',
        'key': 'Dm',
        'artists': [],
        'alt_titles': [],
    },
    'svyat-nash-gospod-chris-tomlin-holy-is-the-lord.md': {
        'title_ru': 'Свят наш Господь',
        'title_en': 'Holy is the Lord',
        'key': 'G',
        'artists': ['Chris Tomlin'],
        'alt_titles': [],
    },
    'svyat-svyat-gospod-savaof.md': {
        'title_ru': 'Свят, свят, Господь Саваоф',
        'title_en': '',
        'key': 'Em',
        'artists': [],
        'alt_titles': [],
    },
    'svyataya-noch-o-holy-night-68.md': {
        'title_ru': 'Святая ночь',
        'title_en': 'O, Holy Night',
        'key': '6/8 - A',
        'artists': [],
        'alt_titles': [],
    },
    'svyatoj-jesus-culture-holy.md': {
        'title_ru': 'Святой',
        'title_en': 'Holy',
        'key': 'Em',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'svyatyj-voveki-bethel-music-holy-forever.md': {
        'title_ru': 'Святый Вовеки',
        'title_en': 'Holy Forever',
        'key': 'G',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'tak-sluchilos-tak-sluchilos.md': {
        'title_ru': 'Так случилось, так случилось',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'takoj-bolshoj-bog-unknown-artist-e.md': {
        'title_ru': 'Такой большой Бог',
        'title_en': '',
        'key': 'E',
        'artists': ['Unknown artist'],
        'alt_titles': [],
    },
    'tam-rcc-worship.md': {
        'title_ru': 'Там',
        'title_en': '',
        'key': 'Gm',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'tolko-ty-gospod-upovanie-moe.md': {
        'title_ru': 'Только Ты, Господь, упование моё',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'tolko-ty-spasitel-matt-redman-you-alone.md': {
        'title_ru': 'Только Ты, Спаситель',
        'title_en': 'You alone',
        'key': 'G',
        'artists': ['Matt Redman'],
        'alt_titles': [],
    },
    'tommee-profitt-noel-he-is-born-34.md': {
        'title_ru': '',
        'title_en': 'Noel (He is born)',
        'key': '3/4 - A',
        'artists': ['Tommee Profitt'],
        'alt_titles': [],
    },
    'tvoe-imya-kak-med-vineyard-worship-holy-and-anointed-one.md': {
        'title_ru': 'Твоё Имя, как мёд',
        'title_en': 'Holy and Anointed One',
        'key': 'G',
        'artists': ['Vineyard Worship'],
        'alt_titles': [],
    },
    'tvoe-imya-prekrasno-bog-hillsong-worship-what-a-beautiful-na.md': {
        'title_ru': 'Твоё имя прекрасно Бог',
        'title_en': 'What a beautiful name',
        'key': 'D',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'tvoya-lyubov-rcc-worship.md': {
        'title_ru': 'Твоя Любовь',
        'title_en': '',
        'key': 'E',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'tvoya-lyubov-spasla-menya-brian-johnson-love-came-down.md': {
        'title_ru': 'Твоя любовь спасла меня',
        'title_en': 'Love came down',
        'key': 'G',
        'artists': ['Brian Johnson'],
        'alt_titles': [],
    },
    'ty-blagoj-bog-crest-music.md': {
        'title_ru': 'Ты благой Бог',
        'title_en': '',
        'key': 'Hm',
        'artists': ['Crest Music'],
        'alt_titles': [],
    },
    'ty-dostoin-slavy-vsej-david-brymer-worthy-of-it-all.md': {
        'title_ru': 'Ты достоин славы всей',
        'title_en': 'Worthy of it all',
        'key': 'A',
        'artists': ['David Brymer'],
        'alt_titles': [],
    },
    'ty-likuj-doch-siona-paul-wilbur-roni-roni-bat-zion.md': {
        'title_ru': 'Ты ликуй, дочь Сиона',
        'title_en': 'Roni Roni Bat Zion',
        'key': 'Am',
        'artists': ['Paul Wilbur'],
        'alt_titles': [],
    },
    'ty-nashel-menya-bog-filipp-renner.md': {
        'title_ru': 'Ты нашёл меня, Бог',
        'title_en': '',
        'key': 'A',
        'artists': ['Филипп Реннер'],
        'alt_titles': [],
    },
    'ty-nuzhen-mne-rcc-worship.md': {
        'title_ru': 'Ты нужен мне',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'ty-odin-takoj-lenny-leblanc-there-is-none-like-you.md': {
        'title_ru': 'Ты Один такой',
        'title_en': 'There is none like You',
        'key': '',
        'artists': ['Lenny LeBlanc'],
        'alt_titles': [],
    },
    'ty-omoj-menya-carpen-diaz.md': {
        'title_ru': 'Ты омой меня',
        'title_en': '',
        'key': 'A',
        'artists': ['Carpen Diaz'],
        'alt_titles': [],
    },
    'ty-prizval-menya-iz-tmy.md': {
        'title_ru': 'Ты призвал меня из тьмы',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'ty-silnee-hillsong-worship-stronger.md': {
        'title_ru': 'Ты сильнее',
        'title_en': 'Stronger',
        'key': 'C',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'ty-sotvorish-chudesa-elevation-worship-do-it-again.md': {
        'title_ru': 'Ты сотворишь чудеса',
        'title_en': 'Do it again',
        'key': 'Bb',
        'artists': ['Elevation Worship'],
        'alt_titles': [],
    },
    'ty-spas-moe-serdce-ryan-ellis-you-saved-me.md': {
        'title_ru': 'Ты спас моё сердце',
        'title_en': 'You saved me',
        'key': 'G',
        'artists': ['Ryan Ellis'],
        'alt_titles': [],
    },
    'ty-zhdesh-kogda-ya-pridu-jesus-culture-you-wont-relent.md': {
        'title_ru': 'Ты ждешь когда я приду',
        'title_en': 'You Won’t Relent',
        'key': 'C#m',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'u-nog-tvoih.md': {
        'title_ru': 'У ног Твоих',
        'title_en': '',
        'key': 'Em',
        'artists': [],
        'alt_titles': [],
    },
    'uchenik-hrista-rcc-worship-e.md': {
        'title_ru': 'Ученик Христа',
        'title_en': '',
        'key': 'E',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'uzok-put-moj-gospod-iisus-hristos.md': {
        'title_ru': 'Узок путь',
        'title_en': '',
        'key': 'C',
        'artists': [],
        'alt_titles': ['Мой Господь — Иисус Христос'],
    },
    'v-tvoej-reke-ozhivaem-jesus-culture-in-the-river.md': {
        'title_ru': 'В Твоей реке оживаем',
        'title_en': 'In the River',
        'key': 'G',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'v-tvoem-prisutstvii-new-life-worship-here-in-your-presence-g.md': {
        'title_ru': 'В Твоём присутствии',
        'title_en': 'Here in Your presence',
        'key': 'G (6/8)',
        'artists': ['New Life Worship'],
        'alt_titles': [],
    },
    'veliki-i-chudny-dela-tvoi.md': {
        'title_ru': 'Велики и чудны дела Твои',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'veryu-ya-phil-wickham-believe.md': {
        'title_ru': 'Верю я',
        'title_en': 'Believe',
        'key': 'A',
        'artists': ['Phil Wickham'],
        'alt_titles': [],
    },
    'viktor-lavrinenko-blagodat-e.md': {
        'title_ru': 'Благодать',
        'title_en': '',
        'key': 'E',
        'artists': ['Виктор Лавриненко'],
        'alt_titles': [],
    },
    'vlyublyayus-v-tebya-iisus-hillsong.md': {
        'title_ru': 'Влюбляюсь в Тебя, Иисус',
        'title_en': '',
        'key': 'G',
        'artists': ['Hillsong'],
        'alt_titles': [],
    },
    'vo-mne-mir-kak-reka-vo-mne-zhizn-kak-reka.md': {
        'title_ru': 'Во мне мир как река',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': ['Во мне жизнь как река'],
    },
    'vot-ya-zdes-deluge-worshipping-you.md': {
        'title_ru': 'Вот я здесь',
        'title_en': 'Worshipping You',
        'key': 'G',
        'artists': ['Deluge'],
        'alt_titles': [],
    },
    'voznosim-golosa-rcc-worship.md': {
        'title_ru': 'Возносим голоса',
        'title_en': '',
        'key': 'G',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'vse-chto-mne-nado.md': {
        'title_ru': 'Всё, что мне надо',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'vse-narody-druzhno-hlopajte-charlie-leblanc-clap-your-hands-.md': {
        'title_ru': 'Все народы, дружно хлопайте',
        'title_en': 'Clap your hands all ye people',
        'key': 'E',
        'artists': ['Charlie LeBlanc'],
        'alt_titles': [],
    },
    'vse-vozmi-hillsong-united-take-it-all.md': {
        'title_ru': 'Всё возьми',
        'title_en': 'Take it all',
        'key': 'H',
        'artists': ['Hillsong United'],
        'alt_titles': [],
    },
    'vsemoguschij-bog-kirk-franklin-he-reigns.md': {
        'title_ru': 'Всемогущий Бог',
        'title_en': 'He reigns',
        'key': 'Dm',
        'artists': ['Kirk Franklin'],
        'alt_titles': [],
    },
    'ya-budu-pet-allilujya-rcc-worship-e.md': {
        'title_ru': 'Я буду петь: «Аллилуйя!»',
        'title_en': '',
        'key': 'E',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'ya-budu-slavit-gospoda-hrista-subcultura.md': {
        'title_ru': 'Я буду славить Господа Христа',
        'title_en': '',
        'key': 'G',
        'artists': ['Subcultura'],
        'alt_titles': [],
    },
    'ya-hvalu-tebe-poyu-gospod-terry-macalmon-i-sing-praise.md': {
        'title_ru': 'Я хвалу Тебе пою, Господь',
        'title_en': 'I sing praise',
        'key': 'G',
        'artists': ['Terry MacAlmon'],
        'alt_titles': [],
    },
    'ya-hvalyus-hristom-hillsong-worship-i-will-boast-in-christ.md': {
        'title_ru': 'Я хвалюсь Христом',
        'title_en': 'I Will Boast In Christ',
        'key': 'Em',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'ya-mogu-lish-predstavit-mercyme-i-can-only-imagine-d.md': {
        'title_ru': 'Я могу лишь представить',
        'title_en': 'I Can Only Imagine',
        'key': 'D',
        'artists': ['MercyMe'],
        'alt_titles': [],
    },
    'ya-naveki-tvoj-galim-husainov-d.md': {
        'title_ru': 'Я навеки Твой',
        'title_en': '',
        'key': 'D',
        'artists': ['Галим Хусаинов'],
        'alt_titles': [],
    },
    'ya-ne-budu-rabom-greha-bethel-music-no-longer-slaves.md': {
        'title_ru': 'Я не буду рабом греха',
        'title_en': 'No longer slaves',
        'key': 'G',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'ya-ne-pokoleblyus-bethel-music-we-will-not-be-shaken.md': {
        'title_ru': 'Я не поколеблюсь',
        'title_en': 'We will not be shaken',
        'key': 'A',
        'artists': ['Bethel Music'],
        'alt_titles': [],
    },
    'ya-ne-veryu-v-poteri-rcc-worship.md': {
        'title_ru': 'Я не верю в потери',
        'title_en': '',
        'key': 'Gm',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'ya-razrushayu-filipp-renner.md': {
        'title_ru': 'Я разрушаю',
        'title_en': '',
        'key': 'A',
        'artists': ['Филипп Реннер'],
        'alt_titles': [],
    },
    'ya-tak-hochu-rcc-worship.md': {
        'title_ru': 'Я так хочу',
        'title_en': '',
        'key': 'Em 6/8',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'ya-tancuyu-dlya-boga.md': {
        'title_ru': 'Я танцую для Бога',
        'title_en': '',
        'key': 'G',
        'artists': [],
        'alt_titles': [],
    },
    'ya-znayu-kto-ya-v-tebe-hillsong-worship-who-you-say-i-am.md': {
        'title_ru': 'Я знаю, кто я в Тебе',
        'title_en': 'Who You say I am',
        'key': 'Hb',
        'artists': ['Hillsong Worship'],
        'alt_titles': [],
    },
    'ya-znayu-ty-zdes-rcc-worship.md': {
        'title_ru': 'Я знаю Ты здесь',
        'title_en': '',
        'key': 'Em',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'yahve-slavu-nam-yavlyaj-oasis-worship-yahweh-se-manifestara.md': {
        'title_ru': 'Яхве, славу нам являй',
        'title_en': 'Yahweh Se Manifestará',
        'key': 'C',
        'artists': ['Oasis Worship'],
        'alt_titles': [],
    },
    'you-raise-me-up-josh-groban.md': {
        'title_ru': '',
        'title_en': 'You raise me up',
        'key': 'Eb',
        'artists': ['Josh Groban'],
        'alt_titles': [],
    },
    'za-kazhdyj-den-gong-spasibo.md': {
        'title_ru': 'За каждый день',
        'title_en': '',
        'key': 'E',
        'artists': ['GONG'],
        'alt_titles': ['Спасибо'],
    },
    'za-to-chto-ryadom-byl-rcc-worship.md': {
        'title_ru': 'За то, что рядом был',
        'title_en': '',
        'key': 'C',
        'artists': ['RCC Worship'],
        'alt_titles': [],
    },
    'zazhgi-v-dushe-moej-ogon-jesus-culture-set-a-fire.md': {
        'title_ru': 'Зажги в душе моей огонь',
        'title_en': 'Set a fire',
        'key': 'G',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'zemlya-uslyshit-slavnyj-golos-carya.md': {
        'title_ru': 'Земля услышит славный голос Царя',
        'title_en': '',
        'key': 'Am',
        'artists': [],
        'alt_titles': [],
    },
    'zhatvy-mnogo-slovo-zhizni.md': {
        'title_ru': 'Жатвы много',
        'title_en': '',
        'key': 'Em',
        'artists': ['Слово Жизни'],
        'alt_titles': [],
    },
    'zhazhdet-tebya-dusha-moya.md': {
        'title_ru': 'Жаждет Тебя душа моя',
        'title_en': '',
        'key': 'E',
        'artists': [],
        'alt_titles': [],
    },
    'zhdem-gospod-tebya-martin-smith-waiting-here-for-you-a.md': {
        'title_ru': 'Ждём, Господь, Тебя',
        'title_en': 'Waiting Here for You',
        'key': 'A',
        'artists': ['Martin Smith'],
        'alt_titles': [],
    },
    'zhertvoj-iisusa-hrista-blagoslovi-dusha-moya-gospoda.md': {
        'title_ru': 'Жертвой Иисуса Христа',
        'title_en': '',
        'key': 'D',
        'artists': [],
        'alt_titles': ['Благослови душа моя, Господа'],
    },
    'zhivu-toboj-jesus-culture-alive-in-you.md': {
        'title_ru': 'Живу Тобой',
        'title_en': 'Alive in You',
        'key': 'H',
        'artists': ['Jesus Culture'],
        'alt_titles': [],
    },
    'zhizn-tvoya-techet-cherez-menya.md': {
        'title_ru': 'Жизнь Твоя течёт через меня',
        'title_en': '',
        'key': 'Hb',
        'artists': [],
        'alt_titles': [],
    },
    'znayu-menya-pobeda-zhdet-elevation-worship-see-a-victory.md': {
        'title_ru': 'Знаю, меня победа ждёт',
        'title_en': 'See a Victory',
        'key': 'G',
        'artists': ['Elevation Worship'],
        'alt_titles': [],
    },
    'zvezd-divnye-almazy-dmitrij-pritula-cerkov-bozhya-v-caricyno.md': {
        'title_ru': 'Звёзд дивные алмазы',
        'title_en': '',
        'key': 'Am',
        'artists': ['Дмитрий Притула', 'Церковь Божья в Царицыно'],
        'alt_titles': [],
    },
}
